services:
  mysql-inventory:
    image: mysql:8.3.0
    container_name: mysql-inventory
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3308:3306" 
    volumes:
      - mysql_inventory_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init_inventory.sql

volumes:
  mysql_inventory_data: